<Project Sdk="Aspire.AppHost.Sdk/13.1.0">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MoreSpeakers</RootNamespace>
        <AssemblyName>MoreSpeakers.AppHosts</AssemblyName>
        <Company>Woodruff Solutions, LLC</Company>
        <Authors>Chris Woodruff, Joseph Guadagno</Authors>
        <Product>More Speakers</Product>
        <Description>The More Speakers Application Hosts</Description>
        <Copyright>Copyright ©2014-2025, Woodruff Solutions, LLC</Copyright>
        <Title>More Speakers - Application Hosts</Title>
        <UserSecretsId>b947c459-0334-4920-8005-4e4d658c9169</UserSecretsId>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <VersionMajor>1</VersionMajor>
        <VersionMinor>4</VersionMinor>
        <VersionBuild>1</VersionBuild>
    </PropertyGroup>
    <PropertyGroup>
        <VersionPrefix>$(VersionMajor).$(VersionMinor).$(VersionBuild)</VersionPrefix>
    </PropertyGroup>
    <PropertyGroup>
        <VersionSuffix Condition=" '$(GITHUB_RUN_ID)' == '' ">local</VersionSuffix>
        <VersionSuffix Condition=" '$(GITHUB_RUN_ID)' != '' And '$(Configuration)' == 'Debug'">$(GITHUB_RUN_ID)-preview</VersionSuffix>
    </PropertyGroup>
    <PropertyGroup>
        <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionPrefix)-$(VersionSuffix)</AssemblyVersion>
        <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">$(VersionPrefix)</AssemblyVersion>
    </PropertyGroup>
    <PropertyGroup>
        <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
        <FileVersion>$(VersionPrefix)</FileVersion>
        <ProductVersion>$(VersionPrefix)($VersionSuffix)</ProductVersion>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\MoreSpeakers.Web.xml</DocumentationFile>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\MoreSpeakers.Web.xml</DocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.1.0" />
        <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.1.1" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
        <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoreSpeakers.Functions\MoreSpeakers.Functions.csproj" />
        <ProjectReference Include="..\MoreSpeakers.Web\MoreSpeakers.Web.csproj" />
    </ItemGroup>

</Project>
