<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-morespeakers-3f5747e1-0cb2-46db-ba42-302d1dccea79</UserSecretsId>
        <AssemblyName>MoreSpeakers.Web</AssemblyName>
        <Company>Woodruff Solutions, LLC</Company>
        <Authors>Chris Woodruff, Joseph Guadagno</Authors>
        <Product>More Speakers - Web</Product>
        <Description>The More Speakers Web application</Description>
        <Copyright>Copyright ©2014-2025, Woodruff Solutions, LLC</Copyright>
        <Title>More Speakers - Web</Title>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\MoreSpeakers.Web.xml</DocumentationFile>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\MoreSpeakers.Web.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Azure.Data.Tables" Version="13.1.0" />
        <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.1.0" />
        <PackageReference Include="Aspire.Azure.Storage.Queues" Version="13.1.1" />
        <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.1.0" />
        <PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.23.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.AssemblyName" Version="2.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoreSpeakers.Data\MoreSpeakers.Data.csproj" />
        <ProjectReference Include="..\MoreSpeakers.Domain\MoreSpeakers.Domain.csproj" />
        <ProjectReference Include="..\MoreSpeakers.Managers\MoreSpeakers.Managers.csproj" />
        <ProjectReference Include="..\MoreSpeakers.ServiceDefaults\MoreSpeakers.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Categories\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Categories\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Categories\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Categories\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Expertises\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Expertises\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Expertises\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Expertises\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Expertises\_ExpertiseCategorySelectItem.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Sectors\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Sectors\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Sectors\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Pages\Expertises\Sectors\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Categories\Create.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Categories\Details.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Categories\Edit.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Categories\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Expertises\Create.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Expertises\Details.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Expertises\Edit.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Expertises\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Expertises\_ExpertiseCategorySelectItem.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Sectors\Create.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Sectors\Details.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Sectors\Edit.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Pages\Catalog\Expertises\Sectors\Index.cshtml" />
    </ItemGroup>
</Project>
